### ISSUE TITLE
Half of examples no work

### ISSUE THREAD

**Issue by freetoair** [sipeed/TangNano-9K-example#21]
Just like other Dev. Boards from SiPEED half of the projects work and half  not. I first bought a MAIXDUINO about a year ago. The same thing, no support, only some demonstration projects work. Then I bought an M0P Dock about a month ago, that board never worked.
  You are a real disappointment to both yours and the manufacturers whose components you use.
  I have no intention of ever buying anything from SiPEED again.

**Comment by wonderfullook** [comment]
Maybe give issue at [sipeed_wiki](https://github.com/sipeed/sipeed_wiki) is better than this paga

**Comment by freetoair** [comment]
Sorry, but after so many failed attempts and time spent on various forums and groups, I have lost patience and desire to continue using your products.

**Comment by freetoair** [comment]
Just to mention that in the meantime I also received the development board GD32VF103CBT6 and of course, as usual, the platformio extension cannot be installed. Quite normal for a SiPEED product.

**Comment by wonderfullook** [comment]
> Just to mention that in the meantime I also received the development board GD32VF103CBT6 and of course, as usual, the platformio extension cannot be installed. Quite normal for a SiPEED product.

As I have said, this is the FPGA page and not for other products. lol
